#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/db_temp?serverTimezone=UTC
#    data-username: root
#    data-password: root
#    driver-class-name: com.mysql.jdbc.Driver

# 日志
logging:
  level:
    com.cjj.mapper: debug

#用来配置错误页面的时候可以拿到exception
server:
  error:
    include-exception: true
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/db_temp?serverTimezone=UTC
    druid:
      filters: stat,wall
      stat-view-servlet:
        enabled: true
        login-password: 123456
        login-username: admin
      web-stat-filter:
        enabled: true
        url-pattern: /**
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
  thymeleaf:
    cache: false


mybatis-plus:
  configuration:
    database-id: mysql
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*.xml

